# MadLibs game
# Word game where you tell the user to fill blanks with corresponding hints to form a story

print("I packed my favorite ____ before heading out.")
blankOne = input("Fill the blank with a Noun: ")
print("As i ____ down the street, something strange happened.")
blankTwo = input("Fill in the blank with a Verb [past tense]: ")
print("The sky turned ____, and I knew this would be no ordinary day.")
blankThree = input("Fill in the blank with an Adjective: ")
print("I decided to take a shortcut through ____.")
blankFour = input("Fill in the blank with a Place: ")
print("Everything was moving ____, as if time had slowed down.")
blankFive = input("Fill in the blank with an Adverb: ")
print("Suddenly, a group of ____ appeared in front of me.")
blankSix = input("Fill in the blank with a Plural Noun: ")
print("I had no choice but to ____ quickly.")
blankSeven = input("Fill in the blank with a Verb: ")
print("My heart was filled with ____ as i ran.")
blankEight = input("Fill in the blank with a Emotion: ")
print("Just then, a ____ blocked my path.")
blankNine = input("Fill in the blank with an Animal: ")
print("\"____!\" I shouted, and everything went black.")
blankTen = input("Fill in the blank with an Exclamation: ")

print()
print(f"I packed my favorite {blankOne} before heading out.")
print(f"As i {blankTwo} down the street, something strange happened.")
print(f"The sky turned {blankThree}, and I knew this would be no ordinary day.")
print(f"I decided to take a shortcut through {blankFour}.")
print(f"Everything was moving {blankFive}, as if time had slowed down.")
print(f"Suddenly, a group of {blankSix} appeared in front of me.")
print(f"I had no choice but to {blankSeven} quickly.")
print(f"My heart was filled with {blankEight} as i ran.")
print(f"Just then, a {blankNine} blocked my path.")
print(f"\"{blankTen}!\" I shouted, and everything went black.")